
FROM nvidia/cuda:9.0-devel


RUN \
  apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --fix-missing --no-install-recommends -y \
  python2.7 \
  python-pip \
  python-setuptools \
  python-dev libxml2-dev libxslt-dev \
  && apt-get update wget \
  && apt-get install -y cmake \
  && apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6 \
  && rm -rf /var/lib/apt/lists/*

RUN curl -O https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
RUN bash Anaconda3-2020.11-Linux-x86_64.sh
